### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by DoubleAJ** [timka/watchdogdev#3]
The latest released version of this package works on **Python 2.7**. 
Since Python 2 was put in end of life since Jan 1st 2020 (see  https://python-release-cycle.glitch.me/), in order to be able to use the package again, it would be necessary to publish a new release compatible with **Python >= 3.5** .
The new release could therefore be published on **PyPi** (it can be done automatically in the "Actions" section), so that it will be publicly available via **pip**.

**Comment by timka** [comment]
@DoubleAJ Sorry for the delay. Managed to setup a workflow that uploads packages to PyPI but now we have to figure out how to build manylinux wheels so that they don't get rejected by PyPI

**Comment by timka** [comment]
It worked!

https://github.com/timka/watchdogdev/runs/474558830

**Comment by DoubleAJ** [comment]
Thank you @timka. 
I tried installing the new version, but unfortunately it didn't work.
By looking at the published package files ( https://pypi.org/simple/watchdogdev/ ), I think the cause seems to be:
- I am trying to install on a Raspberry Pi (**armv6l**), but only **x86_64** wheels were built;
- When the appropriate wheel is not available, the system goes ahead and builds the package from the sources, however the archive containing the sources for v1.0.0 wasn't published (only the v0.11 archive is present).

Do you think you could modify the script so that the sources are added too?

Here is the output of the installation attempt:
```
pi@raspberrypi:~ $ python3 -m pip install -v watchdogdev==1.0.0
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-dvj0amsz
Created temporary directory: /tmp/pip-req-tracker-6iw3vc6h
Initialized build tracking at /tmp/pip-req-tracker-6iw3vc6h
Created build tracker: /tmp/pip-req-tracker-6iw3vc6h
Entered build tracker: /tmp/pip-req-tracker-6iw3vc6h
Created temporary directory: /tmp/pip-install-y03zbb94
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2 location(s) to search for versions of watchdogdev:
* https://pypi.org/simple/watchdogdev/
* https://www.piwheels.org/simple/watchdogdev/
Fetching project page and analyzing links: https://pypi.org/simple/watchdogdev/
Getting page https://pypi.org/simple/watchdogdev/
Found index url https://pypi.org/simple
Getting credentials from keyring for https://pypi.org/simple
Getting credentials from keyring for pypi.org
Looking up "https://pypi.org/simple/watchdogdev/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/watchdogdev/ HTTP/1.1" 304 0
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/85/82/490ca165bb344bbfb817ece0f9c28a3369aa9e0c750456c500626f5449f1/watchdogdev-0.11-py2.6-linux-i686.egg#sha256=4fc9ff259f98715bb81a2416f2962b71dceb026fa6568a89b47ba5a8b22690e7 (from https://pypi.org/simple/watchdogdev/)
  Found link https://files.pythonhosted.org/packages/97/3d/1e96e2de0d9bbefd57cccf9981cc178e6900767e324538d5795e36576565/watchdogdev-0.11.tar.gz#sha256=5666b79a08bccca16d3be0f6f0d6f37c0d020ed22dc9ba72304d878c62490967 (from https://pypi.org/simple/watchdogdev/), version: 0.11
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://files.pythonhosted.org/packages/f4/e0/0d14c417d39c92b60e8f1eca87b6628a5dd07073e3d379e9cf5623da519b/watchdogdev-1.0.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=89b39471e5d0bd76f0de16a7c4a7e80394f166fd26893611f56dfe88fdf49fe7 (from https://pypi.org/simple/watchdogdev/) (requires-python:>=2.7, <4)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux2010_x86_64: https://files.pythonhosted.org/packages/10/2f/6472995b30a9b2e574fda7b8956ba374ea4cc8372bf9e8183eff6e77ff0e/watchdogdev-1.0.0-cp36-cp36m-manylinux2010_x86_64.whl#sha256=2ba234ff14196fec66153845ec5698aead4e9c1d9add37395835c059581e089b (from https://pypi.org/simple/watchdogdev/) (requires-python:>=2.7, <4)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://files.pythonhosted.org/packages/56/66/91595b09303cf44faaef91adb4391401f04d0a15acf49dc094624afb5224/watchdogdev-1.0.0-cp37-cp37m-manylinux1_x86_64.whl#sha256=2f3679bbe00215bf27ff2e84f194da95a0cd781b57adca3feb000147567b6620 (from https://pypi.org/simple/watchdogdev/) (requires-python:>=2.7, <4)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux2010_x86_64: https://files.pythonhosted.org/packages/fe/e4/d86728748e78072c6e091410a42b018d7304fe2b092f2bd4e6dc85a43b04/watchdogdev-1.0.0-cp37-cp37m-manylinux2010_x86_64.whl#sha256=adc1c0d78bd1724beed9214a0cef3ecc25d579720f1c3eece5ae1bbdeca6a7bf (from https://pypi.org/simple/watchdogdev/) (requires-python:>=2.7, <4)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://files.pythonhosted.org/packages/09/66/ca40346fc94824f00635e860765769e8ef863fdca1f0800925c2350a8795/watchdogdev-1.0.0-cp38-cp38-manylinux1_x86_64.whl#sha256=6f0311c839d8dc75a883b3b754415d9dc4cdcf4bf82b1ff29919b24e61755e80 (from https://pypi.org/simple/watchdogdev/) (requires-python:>=2.7, <4)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux2010_x86_64: https://files.pythonhosted.org/packages/6e/9f/4293a15ef9f176e50793e2466cc0f1de190df351db8fba049d8219a48532/watchdogdev-1.0.0-cp38-cp38-manylinux2010_x86_64.whl#sha256=c1fdc311370d66cb6b1a3fcbcf244d02cdb93c360c32c720202252f6eb4b8146 (from https://pypi.org/simple/watchdogdev/) (requires-python:>=2.7, <4)
Fetching project page and analyzing links: https://www.piwheels.org/simple/watchdogdev/
Getting page https://www.piwheels.org/simple/watchdogdev/
Found index url https://www.piwheels.org/simple
Getting credentials from keyring for https://www.piwheels.org/simple
Getting credentials from keyring for www.piwheels.org
Looking up "https://www.piwheels.org/simple/watchdogdev/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): www.piwheels.org:443
https://www.piwheels.org:443 "GET /simple/watchdogdev/ HTTP/1.1" 200 98
Updating cache with response from "https://www.piwheels.org/simple/watchdogdev/"
Caching due to etag
Given no hashes to check 0 links for project 'watchdogdev': discarding no candidates
ERROR: Could not find a version that satisfies the requirement watchdogdev==1.0.0 (from versions: 0.11)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-6iw3vc6h'
ERROR: No matching distribution found for watchdogdev==1.0.0
Exception information:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 927, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for watchdogdev==1.0.0
```

**Comment by timka** [comment]
@DoubleAJ Oh, sorry to hear that. I think getting ARM arch support is more valuable for this project. I'll try to figure something out to build ARM wheels as well.

**Comment by timka** [comment]
Maybe [piwheels](https://www.piwheels.org/) is a way to go.

See https://github.com/pypa/manylinux/issues/84

**Comment by timka** [comment]
@DoubleAJ I updated the workflow to build & upload sdist package as well. I think it's better to close this issue and open another one for ARM arch #4
